{
 "title": "OTEL metrics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "label": "Environment", "query": { "query": "label_values(environment)" } },
   {
    "name": "microservice",
    "label": "Microservice",
    "query": {
     "query": "label_values({environment=\"$environment\"},microservice)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Rpc Call Duration",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(rpc_call_duration_ms_sum{environment=\"$environment\", microservice=\"$microservice\"}[5m]) / (rate(rpc_call_duration_ms_count{environment=\"$environment\", microservice=\"$microservice\"}[5m]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "RPC request total",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_requests_total{environment=\"$environment\", microservice=\"$microservice\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Rpc Call Errors Total",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rpc_call_errors_total{environment=\"$environment\", microservice=\"$microservice\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Duration of outbound HTTP requests",
   "type": "histogram",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "http_client_request_duration_count{environment=\"$environment\", microservice=\"$microservice\"}",
     "legendFormat": "{{server_address}} - {{http_request_method}} - {{http_response_status_code}}"
    }
   ]
  }
 ]
}