services:
  backend:
    image: ${IMAGE_NAME:TAG}
    container_name: backend
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
      - example

networks:
  example:
    name: example