services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      # - ./site:/srv
      - ./caddy_data:/data
      - ./caddy_config:/config
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:2019/metrics || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  backend:
    name: backend
    external: true
