services:
  postgres:
    image: postgres:17.6
    container_name: postgres
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example123
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - backend
