services:
  postgres:
    image: postgres:16.3
    container_name: postgres
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example123
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'"]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - ez-miniapp

networks:
  ez-miniapp:
    name: ez-miniapp
