services:
  postgres:
    image: postgres:16.3
    container_name: postgres
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
    networks:
      - example

  backend:
    image: ${IMAGE_NAME:TAG}
    container_name: backend
    restart: always
    ports:
      - 3000:3000
    env_file:
      - backend.env
    networks:
      - example

networks:
  example:
    name: example
