services:
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    command: --config.file=/mnt/config/promtail-config.yaml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail-config.yaml:/mnt/config
      # - /var/lib/docker/containers/:/var/lib/docker/containers/
    ports:
      - 9080:9080
    networks:
      - grafana