services:
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    command: --config.file=/config/promtail.yaml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/config
      - ./data:/data/promtail
      # - /var/lib/docker/containers/:/var/lib/docker/containers/
    ports:
      - 9080:9080
    networks:
      - monitoring