server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9080

# Uncomment for standard logs
positions:
  filename: "/data/promtail/positions.yaml"

# Push to loki
clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: name
            values: [stage-bot]

    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: '\/?(.*)'
        # regex: '\/?(nginx|grafana)'
        target_label: container_name
      - source_labels: ["__meta_docker_container_id"]
        target_label: "container_id"
      - target_label: label_name
        replacement: example

    pipeline_stages:
      - docker: {}
      - json:
          expressions:
            level: log_level
            msg: message

  - job_name: "api"
    syslog:
      listen_address: 0.0.0.0:1514
      labels:
        job: "api"
        service: "api"
    relabel_configs:
      - source_labels: ["__syslog_message_hostname"]
        target_label: "hostname"

  - job_name: system
    pipeline_stages:
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs # A `job` label is fairly standard in prometheus and useful for linking metrics and logs.
          host: yourhost # A `host` label will help identify logs from this machine vs others
          __path__: /var/log/*.log
