server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: "api"
    syslog:
      listen_address: 0.0.0.0:1514
      labels:
        job: "api"
        service: "api"
    relabel_configs:
      - source_labels: ['__syslog_message_hostname']
        target_label: 'api'

  - job_name: "bot"
    syslog:
      listen_address: 0.0.0.0:1515
      labels:
        job: "bot"
        service: "bot"
    relabel_configs:
      - source_labels: ['__syslog_message_hostname']
        target_label: 'bot'