services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    user: '0'
    ports:
      - '3000:3000'
    volumes:
      - './grafana_storage:/var/lib/grafana'
    environment:
     - GF_SERVER_ROOT_URL=http://my.grafana.server
     - GF_INSTALL_PLUGINS=grafana-clock-panel
     - GF_SECURITY_ADMIN_USER=admin
     - GF_SECURITY_ADMIN_PASSWORD=z3n53J55EvS
    networks:
      - monitoring