{
 "title": "Subgraph test",
 "tags": [ "subgraph" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "General/Node status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPC status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eth_rpc_status{instance=\"subgraph-test\"}",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Ethereum Chain Head",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ethereum_chain_head_number{instance=\"subgraph-test\", network=\"mainnet\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Deployments",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deployment_count{instance=\"subgraph-test\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Deployments",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deployment_running_count{instance=\"subgraph-test\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ethereum/Chain Head",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latest Block",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "chain_head_cache_latest_block{instance=\"subgraph-test\", network=\"mainnet\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Oldest block",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 5, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "chain_head_cache_oldest_block{instance=\"subgraph-test\", network=\"mainnet\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Chain Head Cache Size",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 10, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "chain_head_cache_num_blocks{instance=\"subgraph-test\", network=\"mainnet\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Chain Head Lag (blocks)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 15, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "clamp_min(chain_head_cache_latest_block{instance=\"subgraph-test\", network=\"mainnet\"} - chain_head_cache_oldest_block{instance=\"subgraph-test\", network=\"mainnet\"}, 0)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Ethereum RPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPC Requests Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(req_type) (\r\n  rate(endpoint_request{instance=\"subgraph-test\", conn_type=\"rpc\", provider=\"mainnet-rpc-0\"}[$__rate_interval])\r\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RPC Requests by Method",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "sum by(req_type, provider) (rate(endpoint_request{instance=\"subgraph-test\", conn_type=\"rpc\", provider=\"mainnet-rpc-0\"}[$__rate_interval]))",
       "legendFormat": "{{provider}}/{{req_type}}"
      }
     ]
    },
    {
     "title": "RPC Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
     "targets": [
      {
       "expr": "sum by(req_type) (rate(endpoint_request{instance=\"subgraph-test\", conn_type=\"rpc\", provider=\"mainnet-rpc-0\", result!=\"success\"}[$__rate_interval]))",
       "legendFormat": "{{req_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RPC Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total RPC Throughput",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(endpoint_request{instance=\"subgraph-test\", conn_type=\"rpc\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "GraphQL/Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query Cache Status",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "rate(query_cache_status_count[$__rate_interval])",
       "legendFormat": "{{cache_status}}"
      }
     ]
    },
    {
     "title": "Query Result Size",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "sum by(le) (rate(query_result_size_bucket{instance=\"subgraph-test\"}[$__rate_interval]))",
       "legendFormat": "≤ {{le}} bytes"
      }
     ]
    },
    {
     "title": "Max Query Result Size",
     "type": "stat",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 45 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max_over_time(\r\n  query_result_max{instance=\"subgraph-test\"}[$__rate_interval]\r\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Postgres/Store",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connection Pool Size",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "store_connection_pool_size_count{pool=\"main\", shard=\"primary\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Checked Out Connections",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 5, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "store_connection_checkout_count{pool=\"main\", shard=\"primary\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Connection Errors",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 10, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(store_connection_error_count{pool=\"main\", shard=\"primary\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Notification Queue Usage",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 15, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "notification_queue_usage{instance=\"subgraph-test\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Notifications Received/Sent",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 20, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "rate(notification_queue_recvd[1m])",
       "legendFormat": "received {{channel}}"
      },
      {
       "expr": "rate(notification_queue_sent[1m])",
       "legendFormat": "sent {{channel}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Metrics/Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Registered Metrics",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "registered_metrics{instance=\"subgraph-test\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Metrics Register Errors",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 5, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "metrics_register_errors{instance=\"subgraph-test\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Metrics Unregister Errors",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 10, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "metrics_unregister_errors{instance=\"subgraph-test\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Query Semaphore Wait",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "query_semaphore_wait_ms{pool=\"main\", shard=\"primary\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Store Connection Wait Time",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 5, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "store_connection_wait_time_ms{pool=\"main\", shard=\"primary\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}