x-logging: &logging
  driver: "json-file"
  options:
    max-size: "100m"
    max-file: "3"

services:
  flyway-migrations:
    container_name: flyway-migrations
    image: flyway/flyway:latest
    command: -url=jdbc:postgresql://postgres:5432/scc -user=user -password=password -validateMigrationNaming="true" -connectRetries=60 migrate
    networks:
      - backend
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      postgres:
        condition: service_healthy

  migrations:
    container_name: migrations
    image: ${IMAGE_NAME:TAG}
    networks:
      - backend
    command:
    depends_on:
      postgres:
        condition: service_healthy

  backend:
    image: ${IMAGE_NAME:TAG}
    container_name: backend
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      flyway-migrations:
        condition: service_completed_successfully
      migrations:
        condition: service_completed_successfully
    logging: *logging
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://localhost:3000/health || exit 1",
        ]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  backend:
    name: backend
