x-logging: &logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  backend:
    image: ${IMAGE_NAME:TAG}
    container_name: backend
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      flyway-migrations:
        condition: service_completed_successfully
      migrations:
        condition: service_completed_successfully
    logging: *logging
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://localhost:3000/health || exit 1",
        ]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  backend:
    name: backend
