services:
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./alertmanager_data:/alertmanager
      - ./alertmanager/:/config
    command:
      - '--config.file=/config/alertmanager.yaml'
      - '--storage.path=/alertmanager'
      - '--web.external-url=http://localhost:9093/'
      # - '--log.level=debug'
    restart: unless-stopped
    ports:
      - "9093:9093"
    networks:
      - monitoring
    labels:
      group: "monitoring"
      host.name: "${HOST_NAME}"
