name: Example workflow

on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths-ignore:
      - .github/workflows/**

env:
    ECR_REGISTRY: ${{ secrets.DEV_AWS_ACCOUNT_ID }}".dkr.ecr."${{ vars.DEV_AWS_REGION }}".amazonaws.com"
    AWS_REGION: ${{ vars.DEV_AWS_REGION }}
      
jobs:
  Lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: Install packages
        run: npm ci

      - name: Lint
        run: npm run lint

  Build:
    runs-on: ubuntu-22.04
    needs: Lint
    env:
      name: ${GITHUB_REPOSITORY#*/}
      tag: ${GITHUB_SHA}
      AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build docker image
        run: |
          docker build . -t ${{ env.ECR_REGISTRY }}/${{ env.name }}:${{ env.tag }}
          docker tag ${{ env.ECR_REGISTRY }}/${{ env.name }}:${{ env.tag }} ${{ env.ECR_REGISTRY }}/${{ env.name }}:latest

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push Docker image to ECR
        run: |
          docker push ${{ env.ECR_REGISTRY }}/${{ env.name }}:${{ env.tag }}
          docker push ${{ env.ECR_REGISTRY }}/${{ env.name }}:latest

  Deploy:
    if: ${{ success() }}
    needs: Build
    runs-on: ubuntu-22.04
    env:
      host: ${{ secrets.DEV_NAME }}@${{ secrets.DEV_IP }}
      ssh-key: "${{ secrets.DEV_SSH_KEY }}"

    steps:
      - name: Create SSH key
        run: |
          echo "${{ env.ssh-key }}" > ssh-key.pem
          sudo chmod 400 ssh-key.pem

      - name: Pull and update services
        run: |
          ssh -i ssh-key.pem -o StrictHostKeyChecking=no ${{ env.host }} ' \
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS \
          --password-stdin ${{ env.ECR_REGISTRY }} ; \
          docker compose -f backend/compose.yaml pull && \
          docker compose -f backend/compose.yaml up -d && \
          docker image prune -af'