name: PROD

on:
  workflow_dispatch:
  push:
    tags:
      - v*.*.*
    paths-ignore:
      - .github/workflows/**

env:
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com
  AWS_REGION: ${{ vars.AWS_REGION }}
  aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
  oidc_role: "role_name"

jobs:
  Build:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    env:
      name: "registry/name"
      tag: ${GITHUB_REF#refs/*/}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ env.aws_account_id }}:role/${{ env.oidc_role }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build docker image
        run: |
          docker build . -t ${{ env.ECR_REGISTRY }}/${{ env.name }}:${{ env.tag }}
          docker tag ${{ env.ECR_REGISTRY }}/${{ env.name }}:${{ env.tag }} ${{ env.ECR_REGISTRY }}/${{ env.name }}:latest

      - name: Push Docker image to ECR
        run: |
          docker push ${{ env.ECR_REGISTRY }}/${{ env.name }}:${{ env.tag }}
          docker push ${{ env.ECR_REGISTRY }}/${{ env.name }}:latest

  Deploy:
    needs: Build
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    env:
      claster_name: ${{ vars.CLUSTER_NAME }}
      service_name: ${{ vars.SERVICE_NAME }}

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ env.aws_account_id }}:role/${{ env.oidc_role }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update ECS service
        run: |
          aws ecs update-service \
          --cluster ${{ env.claster_name }} \
          --service ${{ env.service_name}} \
          --force-new-deployment
