name: Backend deploy

on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths-ignore:
      - ".github/workflows/**"
env:
  SSH_KEY: ${{ secrets.DEV_SSH_KEY }}
  IMAGE_NAME: ${GITHUB_REPOSITORY#*/}"-dev"
  IMAGE_TAG: ${{ github.sha }}
  HOST: ${{ secrets.DEV_NAME }}@${{ secrets.DEV_IP }}

jobs:
  Build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build docker image
        run: |
          docker build . -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Save docker image
        run: |
          docker save -o ${{ env.IMAGE_NAME }}.tar ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Generate SSH key
        run: |
          echo "${{ env.ssh-key }}" > ssh-key.pem
          sudo chmod 400 ssh-key.pem

      - name: Copy image to EC2
        run: |
          scp -i ssh-key.pem -o StrictHostKeyChecking=no ${{ env.IMAGE_NAME }}.tar ${{ env.HOST }}:${{ env.IMAGE_NAME }}.tar

  Deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Generate SSH key
        run: |
          echo "${{ env.ssh-key }}" > ssh-key.pem
          sudo chmod 400 ssh-key.pem

      - name: Start image
        run: |
          ssh -i ssh-key.pem -o StrictHostKeyChecking=no ${{ env.HOST }} ' \
          sudo docker load -i '${{ env.IMAGE_NAME }}'.tar && \
          sudo docker stop '${{ env.IMAGE_NAME }}' ; \
          sudo docker run -d --restart always -p '${{ vars.PORT }}':'${{ vars.PORT }}' \
          -e DATABASE_URL='${{ secrets.DATABASE_URL }}' \
          -e HASHER_IV='${{ secrets.HASHER_IV}}' \
          -e HASHER_SECRET_KEY='${{ secrets.HASHER_SECRET_KEY }}' \
          -e REDIS_HOST='${{ secrets.REDIS_HOST }}' \
          -e REDIS_PORT='${{ secrets.REDIS_PORT }}' \
          -e REDIS_URL='${{ secrets.REDIS_URL }}' \
          -e REDIS_JWT_REFRESH_EXPIRATION='${{ secrets.REDIS_JWT_REFRESH_EXPIRATION }}' \
          -e SWAGGER_VERSION='${{ vars.SWAGGER_VERSION }}' \
          -e HOST='${{ vars.HOST }}' \
          -e PORT='${{ vars.PORT }}' \
          --network weway \
          --name '${{ env.IMAGE_NAME }}'-new '${{ env.IMAGE_NAME }}':'${{ env.IMAGE_TAG }}' && \
          sudo docker rm '${{ env.IMAGE_NAME }}' && sudo docker rmi $(sudo docker images -q); \
          sudo docker rename '${{ env.IMAGE_NAME }}'-new '${{ env.IMAGE_NAME }}' && \
          rm '${{ env.IMAGE_NAME }}'.tar'
