groups:
  - name: Instance Access
    rules:
      - alert: Instance Access
        expr: probe_success == 0
        for: 30s
        labels:
          severity: Critical
          instance: Test instance
        annotations:
          summary: "Instance {{ $labels.instance }}"
