services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:25.7.4
    container_name: clickhouse
    ports:
     - 8123:8123
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_DB=stars
      - CLICKHOUSE_USER=stars
      - CLICKHOUSE_PASSWORD=tHEYjUla6STPJr
    volumes:
      - ./data:/var/lib/clickhouse
      - ./logs:/var/log/clickhouse-server
    restart: unless-stopped
    networks:
      - clickhouse

networks:
  clickhouse:
    name: clickhouse