services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - ./prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus/'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=30d'
      - '--storage.tsdb.retention.size=50GB'
      # - '--storage.tsdb.wal-compression=true'
      - '--storage.tsdb.min-block-duration=2h'
      - '--storage.tsdb.max-block-duration=24h'
      - '--web.external-url=${PROMETHEUS_URL:-http://localhost:9090}'
      - '--web.enable-admin-api'
    restart: unless-stopped
    ports:
      - "0.0.0.0:${PROMETHEUS_PORT:-9090}:9090"
    networks:
      - monitoring
    labels:
      group: "monitoring"
      host.name: "${HOST_NAME}"