# log:
#   level: DEBUG

accessLog:
  filePath: "/data/log/access.log"
  bufferingSize: 100
  format: json
metrics:
  prometheus:
    manualRouting: true
    addRoutersLabels: true

api:
  insecure: false
  dashboard: true

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
    network: leaderboard-calculation
  file:
    filename: /config/traefik.config.yaml
    watch: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: secureweb
          scheme: https

  secureweb:
    address: :443
    http:
      tls:
        certResolver: myresolver
        domains:
          - main: strapi-dollar.blaize.technology
            sans: "*.strapi-dollar.blaize.technology"

certificatesResolvers:
  myresolver:
    acme:
      storage: /data/acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0
