services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./users.yml:/data/users.yml:ro
    ports:
      - 8080:8080
    environment:
      DOZZLE_BASE: /logs
      DOZZLE_AUTH_PROVIDER: simple
