groups:
  - name: Service Access
    rules:
      - alert: Service Access
        expr: probe_success == 0
        for: 2m
        labels:
          severity: Critical
          # instance: "{{ $labels.instance }}"
          # service: "{{ $labels.service }}"
        annotations:
          summary: "Service access failure"
          description: "Target {{ $labels.instance }} is unreachable."
