services:
  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus-data:/prometheus
    labels:
      traefik.enable: true
      traefik.http.routers.prometheus.rule: Host(`prometheus.${BLAIZE_DOMAIN}`)
      traefik.http.routers.prometheus.entrypoints: secureweb
      traefik.http.routers.prometheus.tls.certresolver: myresolver
      traefik.http.routers.prometheus.middlewares: forward-auth@file
    networks:
      - leaderboard-calculation
  grafana:
    image: grafana/grafana-enterprise
    restart: always
    volumes:
      - grafana-data:/var/lib/grafana
    labels:
      traefik.enable: true
      traefik.http.routers.grafana.rule: Host(`grafana.${BLAIZE_DOMAIN}`)
      traefik.http.routers.grafana.entrypoints: secureweb
      traefik.http.routers.grafana.tls.certresolver: myresolver
      traefik.http.routers.grafana.middlewares: forward-auth@file
    networks:
      - leaderboard-calculation

networks:
  leaderboard-calculation:
    name: leaderboard-calculation
    external: true

volumes:
  grafana-data:
  prometheus-data:
