variables:
  ECR_REGISTRY: "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"
  SSH_KEY: $DEV_SSH_KEY
  SSH_USER: $DEV_SSH_USER
  SSH_IP: $DEV_SSH_IP

stages:
  # - test
  - build
  - deploy

# sast:
#   stage: test
# include:
# - template: Security/SAST.gitlab-ci.yml

build:
  stage: build
  only:
    - dev
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - |
      /kaniko/executor \
        --context $CI_PROJECT_DIR \
        --dockerfile $CI_PROJECT_DIR/Dockerfile \
        --target api \
        --destination $ECR_REGISTRY/podproza/dev-api:$CI_COMMIT_SHORT_SHA \
        --destination $ECR_REGISTRY/podproza/dev-api:latest \
        --cache=true \
        --cache-repo=$ECR_REGISTRY/podproza/cache

    - |
      /kaniko/executor \
        --context $CI_PROJECT_DIR \
        --dockerfile $CI_PROJECT_DIR/Dockerfile \
        --target worker \
        --destination $ECR_REGISTRY/podproza/dev-worker:$CI_COMMIT_SHORT_SHA \
        --destination $ECR_REGISTRY/podproza/dev-worker:latest \
        --cache=true \
        --cache-repo=$ECR_REGISTRY/podproza/cache

deploy:
  stage: deploy
  needs: [build]
  only:
    - dev
  image: alpine:3.18
  before_script:
    - cat $SSH_KEY | base64 -d > ssh-key.pem
    - chmod 400 ssh-key.pem
    - apk add --no-cache openssh-client
    - ls -la
    - cat ssh-key.pem
  script:
    - |
      ssh -i ssh-key.pem -o StrictHostKeyChecking=no $SSH_USER@$SSH_IP "
        aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin $ECR_REGISTRY
        docker compose -f backend/compose.yaml up -d
        docker image prune -af
        "
