services:
  nats:
    image: nats:2.10.26
    container_name: nats
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222"
    environment:
      - NATS_SERVER_NAME=nats-server
    volumes:
      - ./nats_data:/data
    command:
      - "--js"
      - "--sd=/data"
      - "--http_port=8222"
    networks:
      - nats

  nats_exporter:
    image: natsio/prometheus-nats-exporter:0.15.0
    container_name: nats_exporter
    restart: always
    depends_on:
      - nats
    networks:
      - nats
    ports:
      - 7777:7777
    command: "-connz -varz -channelz -serverz -subz -healthz -routez http://nats:8222"

networks:
  nats:
    name: nats
